version: 2

test-template: &test-template
  working_directory: ~/YODO
  steps:
    - run: apt update && apt install -y --no-install-recommends git
    - checkout
    - run: pip3 install -r requirements.txt -r test-requirements.txt
    - run: pytest tests.py

jobs:
  py36:
    docker:
      - image: python:3.6-slim
    <<: *test-template

  py37:
    docker:
      - image: python:3.7-slim
    <<: *test-template

workflows:
  version: 2

  test:
    jobs: &all-tests
      - py36
      - py37

  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs: *all-tests
